server:
  port: 8082

spring:
  application:
    name: microservice-aws

  aws:
    secret:
      key: SECRET_KEY_HIDDEN
    access:
      key: ACCESS_KEY_HIDDEN
    region: us-east-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
