server:
  port: 8088

spring:
  application:
    name: microservice-search

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

cache:
  ttl:
    flight-search: 300 # 5 minutos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/