server:
  port: 8089

spring:
  application:
    name: microservice-payment

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: ken123

  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# PayPal Configuration
paypal:
  mode: sandbox  # sandbox o live
  client-id: YOUR_PAYPAL_CLIENT_ID
  client-secret: YOUR_PAYPAL_CLIENT_SECRET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/