server:
  port: 8088

spring:
  application:
    name: microservice-search

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_db
    username: root
    password: ken123

  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

cache:
  ttl:
    flight-search: 300 # 5 minutos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/