server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type
            maxAge: 3600

      routes:
        # Auth service - Solo endpoints de validación
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # AWS service
        - id: aws-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/aws/**
          filters:
            - StripPrefix=0

        # Flight service
        - id: flight-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/flights/**,/api/aircraft/**,/api/routes/**
          filters:
            - StripPrefix=0

        # Booking service
        - id: booking-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=0

        # Pricing service
        - id: pricing-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/pricing/**
          filters:
            - StripPrefix=0

        # Search service
        - id: search-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=0

        # Payment service
        - id: payment-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0

        # Notifications service
        - id: notifications-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0

security:
  service:
    url: http://localhost:8081/api/auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true