server:
  port: 8081

spring:
  application:
    name: msvc-auth-oauth2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_oauth2_db
    username: root
    password: ken123

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6380

  security:
    oauth2:
      resourceserver:
        jwt:
          # IMPORTANTE: Estas deben coincidir con tu configuración de Auth0
          issuer-uri: https://dev-chzcisisthlmydkb.us.auth0.com/
          # Auth0 usa el endpoint /.well-known/jwks.json para las claves públicas
          jwk-set-uri: https://dev-chzcisisthlmydkb.us.auth0.com/.well-known/jwks.json

# Configuración de Auth0 (debe coincidir con tu aplicación en Auth0 Dashboard)
auth0:
  domain: dev-chzcisisthlmydkb.us.auth0.com
  # CRÍTICO: Este audience DEBE estar configurado en tu Auth0 API
  audience: https://api.miapp.com

  # Credenciales de la aplicación (solo para desarrollo/testing)
  # En producción, NO incluir estas credenciales aquí
  client-id: zaSgoGFBnnNkvlUbNJv9qMrADRJn4wbp
  client-secret: Gr95txgUIxdbs4EZDfEQRKqtf6oYcvsAI-gj42Ufu2zOb-4fxiQO5zJqjQuIUzmD

app:
  frontend:
    url: http://localhost:3000
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true